### ISSUE TITLE
PicGo 2.3.1正式版 插件安装失败

### ISSUE THREAD

**Issue by ZidongY** [yabostone/picgo-plugin-rclone#10]
直接是本地安装操作，PicGo日志显示：
2023-11-13 13:40:54 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module 'C:\Users\yinzi\AppData\Roaming\picgo\node_modules\picgo-plugin-rclone\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at gt.getPlugin (D:\Server\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:40557)
    at gt.registerPlugin (D:\Server\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:39680)
-------Error Stack End-------

**Comment by yabostone** [comment]
您好，您是否考虑了解更多的nodejs的package的配置文件机制和配置方法。
